-- Thirsty Dreamer website CMS — run once in Supabase SQL Editor.
-- 1) Create the administrator account in Supabase Auth first.
-- 2) Replace the UUID below with that account's auth.users.id.
-- 3) Run this full script in the Supabase SQL Editor.
-- The site uses only the public/publishable key in browsers. Never use service_role here.

create table if not exists public.cms_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.cms_admins enable row level security;
revoke all on table public.cms_admins from anon, authenticated;
grant select on table public.cms_admins to authenticated;
drop policy if exists "Admins can verify admin membership" on public.cms_admins;
create policy "Admins can verify admin membership" on public.cms_admins
  for select to authenticated
  using (user_id = (select auth.uid()));

-- Bootstrap exactly the administrator account you intend to use.
-- Replace 00000000-0000-0000-0000-000000000000 before running.
insert into public.cms_admins (user_id)
values ('00000000-0000-0000-0000-000000000000'::uuid)
on conflict (user_id) do nothing;

create or replace function public.is_site_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.cms_admins
    where user_id = (select auth.uid())
  );
$$;
revoke all on function public.is_site_admin() from public;
grant execute on function public.is_site_admin() to authenticated;

create table if not exists public.site_content (
  page_id text primary key check (page_id = 'home'),
  content jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
alter table public.site_content enable row level security;
revoke all on table public.site_content from anon, authenticated;
grant select on table public.site_content to anon, authenticated;
grant insert, update on table public.site_content to authenticated;
drop policy if exists "Public can read published site content" on public.site_content;
drop policy if exists "Admins can create site content" on public.site_content;
drop policy if exists "Admins can update site content" on public.site_content;
create policy "Public can read published site content" on public.site_content
  for select to anon, authenticated using (true);
create policy "Admins can create site content" on public.site_content
  for insert to authenticated with check (public.is_site_admin() and updated_by = (select auth.uid()));
create policy "Admins can update site content" on public.site_content
  for update to authenticated using (public.is_site_admin())
  with check (public.is_site_admin() and updated_by = (select auth.uid()));

create table if not exists public.waitlist_signups (
  id bigint generated by default as identity primary key,
  email text not null check (length(email) <= 320 and email = lower(trim(email))),
  signup_type text not null check (signup_type in ('dream_journal', 'secret_diners')),
  created_at timestamptz not null default now(),
  unique(email, signup_type)
);
alter table public.waitlist_signups enable row level security;
revoke all on table public.waitlist_signups from anon, authenticated;
grant insert on table public.waitlist_signups to anon, authenticated;
grant select on table public.waitlist_signups to authenticated;
grant usage, select on sequence public.waitlist_signups_id_seq to anon, authenticated;
drop policy if exists "Visitors can join an email list" on public.waitlist_signups;
drop policy if exists "Admins can view email signups" on public.waitlist_signups;
create policy "Visitors can join an email list" on public.waitlist_signups
  for insert to anon, authenticated
  with check (signup_type in ('dream_journal', 'secret_diners') and email = lower(trim(email)));
create policy "Admins can view email signups" on public.waitlist_signups
  for select to authenticated using (public.is_site_admin());

-- Publicly readable media, writable only by an administrator.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-media',
  'site-media',
  true,
  52428800,
  array['video/mp4','video/webm','video/quicktime','image/jpeg','image/png','image/webp','image/avif']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public may read site media" on storage.objects;
drop policy if exists "Site admins may upload media" on storage.objects;
drop policy if exists "Site admins may update media" on storage.objects;
drop policy if exists "Site admins may delete media" on storage.objects;
create policy "Public may read site media" on storage.objects
  for select to anon, authenticated using (bucket_id = 'site-media');
create policy "Site admins may upload media" on storage.objects
  for insert to authenticated with check (bucket_id = 'site-media' and public.is_site_admin());
create policy "Site admins may update media" on storage.objects
  for update to authenticated using (bucket_id = 'site-media' and public.is_site_admin())
  with check (bucket_id = 'site-media' and public.is_site_admin());
create policy "Site admins may delete media" on storage.objects
  for delete to authenticated using (bucket_id = 'site-media' and public.is_site_admin());
